name: hear_ai_demo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  go_router: ^13.2.0
  sqflite: ^2.3.2
  flutter_riverpod: ^2.4.10


dependency_overrides:
  material_color_utilities: ^0.8.0

flutter:
  uses-material-design: true
